### ISSUE TITLE
Cannot connect to Neo4J 4.0

### ISSUE THREAD

**Issue by ukirik** [corwur/cytoscapeneo4j#8] opened 2020-06-10 10:45 UTC
Started having connection problems after upgrading the neo4J version to 4.0. Essentially nothing really happens when I click connect. I double checked the user id and password, going via Neo4J browser is no prob either.

My guess is that the auth protocol details have changed. Any insights on this? Can anyone confirm or deny that?

**Comment by swarris** [comment] 2020-06-10 11:07
Indeed, in version 4 they removed the default encryption. It might be fixed by updating the neo4j driver: https://neo4j.com/developer/java but I did not test this yet. Java 8 is supported, so it should be okay.

**Comment by ukirik** [comment] 2020-06-15 09:55
I have tried to rebuild the plugin with the updated driver but keep running into OSGi errors which prevent the App from loading in Cytoscape, especially this one: 

```
Caused by: org.osgi.framework.BundleException: Unable to resolve nl.corwur.cytoscape.neo4j [123](R 123.0): missing requirement [nl.corwur.cytoscape.neo4j [123](R 123.0)] osgi.wiring.package; (osgi.wiring.package=com.google.protobuf) Unresolved requirements: [[nl.corwur.cytoscape.neo4j [123](R 123.0)] osgi.wiring.package; (osgi.wiring.package=com.google.protobuf)]
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4149) ~[?:?]
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2119) ~[?:?]
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:998) ~[?:?]
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:984) ~[?:?]
	at org.cytoscape.app.internal.manager.BundleApp.start(BundleApp.java:82) ~[?:?]
	... 8 more
```

I am not very familiar with the OSGi framework, so I haven't been able to troubleshoot it effectively. Do you have any insights as to what might be causing this?

**Comment by swarris** [comment] 2020-06-15 22:38
It is indeed a little more complex than added the new driver... 
I get now this:
`Caused by: org.osgi.framework.BundleException: Unable to resolve nl.corwur.cytoscape.neo4j [194](R 194.0): missing requirement [nl.corwur.cytoscape.neo4j [194](R 194.0)] osgi.wiring.package; (&(osgi.wiring.package=com.google.protobuf)(version>=3.11.0)(!(version>=4.0.0))) Unresolved requirements: [[nl.corwur.cytoscape.neo4j [194](R 194.0)] osgi.wiring.package; (&(osgi.wiring.package=com.google.protobuf)(version>=3.11.0)(!(version>=4.0.0)))]
`

I'm looking into this.

**Comment by swarris** [comment] 2020-07-03 19:15
It was a little bit more complicated than expected. The branch [driver-upgrade](https://github.com/corwur/cytoscapeneo4j/tree/driver-upgrade) contains the new driver implementation. We are still testing it, but you might want to have a go at it as well.

**Closed** 2020-07-17 11:58 UTC
